codecov:
  # Require CI to pass before considering coverage status
  require_ci_to_pass: yes
  # Don't wait for multiple CI builds
  notify:
    wait_for_ci: no

# Coverage status checks - informational only, won't block PRs
coverage:
  status:
    project:
      default:
        # Informational only - don't fail the build
        informational: true
        target: auto
        threshold: 0%
    patch:
      default:
        # Informational only - don't fail the build
        informational: true
        target: auto
        threshold: 0%

# Comment on PRs with coverage information
comment:
  layout: "header, diff, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

# Ignore paths that shouldn't count toward coverage
ignore:
  - "**/*.spec.ts"
  - "**/*.cy.ts"
  - "**/test-setup.ts"
  - "**/jest.config.ts"
  - "**/cypress.config.ts"
  - "**/*.d.ts"
  - "**/node_modules/**"
  - "dist/**"
  - "coverage/**"
  - "tools/**"
  - "scripts/**"
  - "docs/**"
