appUrl := "https://app.dev.dasch.swiss"

# List all the available targets
default:
    @just --list

# Run the test locally
run:
    APP_URL={{appUrl}} k6 run first-page-load.js

# Run the test in k6 cloud
run-cloud:
    APP_URL={{appUrl}} k6 cloud first-page-load.js
