export { Session } from './lib/session';
export { CurrentUser } from './lib/session';
export { AuthError } from './lib/error';
export { AuthService } from './lib/auth.service';
export { AccessTokenService } from './lib/access-token.service';
export { AutoLoginService } from './lib/auto-login.service';
export { LocalStorageWatcherService } from './lib/local-storage-watcher.service';
export { UserService } from './lib/user.service';
export { ResourceCreationServiceInterface, ResourceCreationOptions } from './lib/resource-creation.service.interface';
export { ResourceFetcherServiceInterface } from './lib/resource-fetcher.service.interface';
export { FootnoteProcessorInterface } from './lib/footnote-processor.interface';
