name: connect

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  connect:
    name: connect
    runs-on: actuated-aarch64
    steps:
      - name: Setup SSH server for Actor
        uses: alexellis/setup-sshd-actor@master
      - name: Connect to the actuated SSH gateway
        uses: alexellis/actuated-ssh-gateway-action@master
        with:
          gatewayaddr: ${{ secrets.SSH_GATEWAY_IP }}
          secure: true
      - name: Setup a blocking tmux session
        uses: alexellis/block-with-tmux-action@master
